branch-defaults:
  main:
    environment: abutsfit
    group_suffix: null
global:
  application_name: abuts.fit
  branch: null
  default_ec2_keyname: null
  profile: abuts.fit
  default_region: ap-south-1
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
